spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/bookstore
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:2104110080A}

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: thenghia25022003@gmail.com
    password: nlunszlvjzxtliss
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    enabled: true


server:
  error:
    include-message: always
  servlet:
    session:
      store-type: none

